### ISSUE TITLE
In samples/generated/v2/function_service.create_function.js, function1 does not exist

### ISSUE THREAD

**Issue by BrianKo14** [googleapis/nodejs-functions#177]
In fact, none of it makes much sense. The `functionId` is never used either.

**Comment by pattishin** [comment]
Hi @BrianKo14 - 
The error you've posted `function1 does not exist` would crop up if you didn't uncomment the stubs we have for `parent` & `function1`. 
https://github.com/googleapis/nodejs-functions/blob/main/samples/generated/v2/function_service.create_function.js#L26

We can add in more guidance on what `functionId` is used for in the sample, but we expect this value to be passed through `createFunction` within the `request` param. Adding docs below for additional color.
 
https://googleapis.dev/nodejs/nodejs-functions/latest/google.cloud.functions.v2beta.FunctionService.html#createFunction1
https://googleapis.dev/nodejs/nodejs-functions/latest/google.cloud.functions.v2beta.ICreateFunctionRequest.html

If this doesn't resolve your concern, let us know.
And if you can some more context to what you're working on, we'd be happy to assist!

**Comment by BrianKo14** [comment]
Hi @pattishin.
`function1` is not defined in the comments either. `function` is.
Incidentally, I understand that by definding this as an empty object you expect whoever uses it to fill in the details for the Function object, is that right? It is a fairly sized request body. An example on how to write it would be very useful.
