### ISSUE TITLE
Make it easier to deploy unauthenticated functions. 

### ISSUE THREAD

**Issue by rswlkr** [googleapis/nodejs-functions#180]
At the moment, to create an unauthenticated function, I have to first deploy using createFunction and then use the [run library](https://github.com/googleapis/nodejs-run) at some indeterminate time after to do this: 

`run.setIamPolicy({
        resource: payload.request.name,
        policy: {
          bindings: [{
            "role": "roles/run.invoker",
            "members": [
              "allUsers"
            ]
          }]
        }
      })` 

Which has meant setting up an audit log trigger with the above.

It should be easier to do this - the gcloud cli for example provides an --allow-unauthenticated flag to do the above step automatically in the function deploy pipeline.

**Comment by sofisl** [comment]
Hi @rswlkr, I think this would be better to raise directly with the [API team](https://issuetracker.google.com/savedsearches/559729) so that they can expose this flag in the client library. Thank you!
