### ISSUE TITLE
Request message serialization failure

### ISSUE THREAD

**Issue by Marcusg62** [googleapis/nodejs-functions#44]
1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
No :(

3) Do you have a support contract?
No :(

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: OS X 10.15.6
  - Node.js version: v12.12.0
  - npm version: 7.0.9
  - `@google-cloud/functions` version: ^1.1.0

#### Intro: 
I am trying to programmatically create a cloud function. However, the function object I am passing gives me the error

`{"code":13,"details":"Request message serialization failure: .google.cloud.functions.v1.CloudFunction.timeout: object expected","metadata":{"internalRepr":{},"options":{}}}`

I copy/pasted my object into the 'Try this API' widget in the API docs and it works. I understand using the API and client library are not a 1:1 match in terms of passing arguments but the documentation matches. Either this is an error on my part or a bug. 

Proof of success in "Try it out" 
![image](https://user-images.githubusercontent.com/21998115/100524874-fddeb680-3178-11eb-9537-1cbdf59b3df6.png)

My Code:

    const {CloudFunctionsServiceClient} = require('@google-cloud/functions');
    const client = new CloudFunctionsServiceClient();
    let myFunction = {
      "name": "projects/senior-design-293721/locations/us-central1/functions/helloWord",
      "sourceUploadUrl": "https://storage.googleapis.com/gcf-upload-us-central1-06164526-5e4b-41ba-98e5-7c2d9a3e7260/4320182d-ea72-4c4a-bfb3-06ecd70ba4b5.zip?GoogleAccessId=service-824226399055@gcf-admin-robot.iam.gserviceaccount.com&Expires=1606527088&Signature=SO%2BSMHRh1iIzyhqQdP4ZA5X4jK5GzAwAVP5ZU%2BaIN1C20Fj3DpwXWY%2BsvVxgQe1m3JlhKu0egfC2mhueUL1j%2BkobjqLRdikg7A6daU0f0tJEUiP6wSZPbmm6zv2Rv9mJXC4inwbR3WwomUHbo%2ByXNJ9F7mHzFDSetJ9rJ5pvkCRbzkPJ%2FLDMgipMz7m7JxDxkQCb8l2l1bkef6zEsoS3DPgTrxKhwuW614ztDzuwenpXeTI295Yo9KusZMvj8juEBfyXszMe3SVFfGRVEOcC8SyQcpkBOtLoU01a1s2oOu5Jr1S%2BpamClKwmIWkfa1NdFVAAGG%2BloP4mhoRP85Ae3g%3D%3D",
      "description": "test",
      "maxInstances": 1000,
      "timeout": "300s",
      "entryPoint": "",
      "httpsTrigger": {},
      "labels": {},
      "network": "",
      "runtime": "nodejs10",
      "serviceAccountEmail": "",
      "vpcConnector": ""
    }

    let request = {
      location: location,
      function: myFunction

    }
    const [operation] = await client.createFunction(request);
    const [response] = await operation.promise();`

#### Steps to reproduce
  1. Follow [Quickstart](https://googleapis.dev/nodejs/nodejs-functions/latest/index.html#quickstart) from Google Cloud Functions: Node.js Client Reference 
  2. Use code noted above to try and create a cloud function. Remember to replace location and name with your respective GCP project info.

**Comment by bcoe** [comment]
@Marcusg62 looking at the type definition, I believe the problem might be that the value of timeout is a `Duration`, not a string (see: https://github.com/googleapis/nodejs-functions/blob/48d5537720622232d8ad139959aecfcf0f3dee54/protos/protos.d.ts#L358).

I think you would write timeout as `{seconds: 300}`.

**Comment by Marcusg62** [comment]
@bcoe Thank you, that was the issue - I feel dumb. 😅 Cheers!

**Comment by Marcusg62** [comment]
@JustinBeckwith Hi, just noticed you assigned me to this? Do I need to do something more to close this out?

**Comment by JustinBeckwith** [comment]
Apologies, robot run amok 🤖

**Comment by pranavig** [comment]
> @Marcusg62 looking at the type definition, I believe the problem might be that the value of timeout is a `Duration`, not a string (see:
> I think you would write timeout as `{seconds: 300}`.

Thank you. This solved the issue
