### ISSUE TITLE
Not showing error messages from Google API 

### ISSUE THREAD

**Issue by koistya** [googleapis/nodejs-functions#62]
#### Environment details

  - OS: `macOS`
  - Node.js version: `14`
  - `@google-cloud/functions`: `1.1.3`

#### Steps to reproduce

  1. Execute any function such as `client.createFunction(...)` with invalid arguments
  2. You will see an error similar to this: `Error: 3 INVALID_ARGUMENT: The request has errors`
      But the actual useful error message from the API is being hidden.

**Comment by boyanstanchev** [comment]
I'm having the exact same issue. All the createFunction options look okay, but I get this error.

**Comment by igor-imaginemage** [comment]
I have been struggling with the same when trying to deploy a v2 function. The github actions script https://github.com/google-github-actions/deploy-cloud-functions is not supporting v2 functions yet, I was trying to contribute with it but these errors are blocking me.

**Comment by sofisl** [comment]
Hi there! We are migrating this repo to googleapis/google-cloud-node. If this is still an issue, please reopen there. Thank you!
